In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("hiring.csv")
dataset.head()

experience  test_score  interview_score  salary
0           1           8                9   50000
1           1           8                6   45000
2           5           6                7   60000
3           2          10               10   65000
4           7           9                6   70000

In [3]:
dataset.shape

(8, 4)

In [4]:
X=dataset.iloc[:, :3]
y=dataset.iloc[:,-1]

In [5]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()

In [6]:
#fitting model with training data
regressor.fit(X,y)

LinearRegression()

In [7]:
regressor.score(X,y)

0.9517383921818203

In [8]:
regressor.intercept_

10234.301838182706

In [9]:
regressor.coef_

array([3158.11642505, 2290.6945836 , 2440.91847793])

In [10]:
regressor.predict([[2,9,6]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([51812.29680823])

## Save the final model

In [11]:
import pickle

In [12]:
#saving model to disk
pickle.dump(regressor,open('model.pkl','wb'))     #wb= writing mode

In [13]:
#loading model to compare the result
reg_model=pickle.load(open('model.pkl','rb'))     #rb=read mode

In [14]:
#compare the results
reg_model.predict([[3,8,9]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60002.47408346])